<a href="https://colab.research.google.com/github/newma2n/Deep-learning-with-pytorch/blob/main/pytorchtutorial1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import torch
import numpy as np

In [49]:
np1=np.random.rand(3,4)
np1


array([[0.79530709, 0.78885141, 0.85003698, 0.27922897],
       [0.96612799, 0.98975317, 0.49249965, 0.19355014],
       [0.40629566, 0.62868127, 0.33871224, 0.76653344]])

In [50]:
tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[-1.5332, -0.2607,  0.5610, -1.6921],
        [ 0.6235, -0.8052,  0.7259,  0.0626],
        [-1.3566, -0.5640,  0.6596, -0.6370]])

In [51]:
tensor_3d =torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [52]:
tensor_4d=torch.zeros(2,2,3,4)
tensor_4d

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])

In [53]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.7953, 0.7889, 0.8500, 0.2792],
        [0.9661, 0.9898, 0.4925, 0.1936],
        [0.4063, 0.6287, 0.3387, 0.7665]], dtype=torch.float64)

In [54]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
my_torch=my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [56]:
my_torch2= torch.arange(10)


In [57]:
my_torch2=my_torch2.reshape(2,5)

my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [58]:
my_torch3=torch.arange(10)

In [59]:
#try to see the differnce between "arange" and "view" methods
my_torch4=my_torch3.view(2,5)

my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [60]:
#slices
my_torch7=torch.arange(10)

my_torch7


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
my_torch7[7]

tensor(7)

In [62]:
#TENSOR MATH OPERATIONS

tensor_a=torch.tensor([1,2,3,4])
tensor_b=torch.tensor([5,6,7,8])

In [63]:
tensor_a +tensor_b

tensor([ 6,  8, 10, 12])

In [64]:
tensor_a*tensor_b

tensor([ 5, 12, 21, 32])

In [65]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [66]:
tensor_a/tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [67]:
tensor_a-tensor_b

tensor([-4, -4, -4, -4])

In [68]:



tensor_a

tensor([1, 2, 3, 4])

In [69]:
tensor_b%tensor_a

tensor([0, 0, 1, 0])

In [70]:
tensor_a**tensor_b


tensor([    1,    64,  2187, 65536])